### ISSUE TITLE
config.toml keyfile ignored when running production release

### ISSUE THREAD

**Issue by mkg20001** [mozilla/reticulum#491]
Currently trying to get a DIY hubs on ubuntu running

Ubuntu 20.04 in LXD deployed with [this script](https://gist.github.com/mkg20001/8e3220f5e39d7c54f644afdb44c8df06)

Added some patches for sql via socket and to fix startup errors
```
    sed "s|hostname: \"localhost\"|socket_dir: \"/run/postgresql\"|g" -i config/prod.exs
    sed "s|username: \"postgres\",|username: \"root\",|g" -i config/prod.exs
    sed "s|password: \"postgres\",|show_sensitive_data_on_connection_error: true,|g" -i config/prod.exs

    sed "s%password = session_lock_db_config |> Keyword.get(:password)%socket_dir = session_lock_db_config |> Keyword.get(:socket_dir)%" -i ./lib/ret/locking.ex
    sed "s|password: password,|socket_dir: socket_dir,|" -i ./lib/ret/locking.ex

    echo 'config :ret, Ret.Habitat, ip: "127.0.0.1", http_port: 9631' >> config/prod.exs
```

Then I compiled with `MIX_ENV=prod mix distillery.release`

Then I added config entries to `_build/prod/rel/ret/config.toml` among others 

```toml
[ret."Elixir.RetWeb.Endpoint".https]
cacertfile = "/var/reticulum/cert-hubs.local.pem"
certfile = "/var/reticulum/cert-hubs.local.pem"
keyfile = "/var/reticulum/key-hubs.local.pem"
port = 4544
```

Now when starting reticulum using `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 REPLACE_OS_VARS=true NODE_NAME=test NODE_COOKIE=testetset _build/prod/rel/ret/bin/ret foreground` it complains about missing keyfile

Also `cat _build/prod/rel/ret/var/sys.config  | grep key` does not contain keyfile

On Hubs Personal AWS it does, even when I directly launch it it picks up config properly.

Can anyone point me to what I'm doing wrong? 

Error msg

```
12:13:54.553 [info] Application ret exited: Ret.Application.start(:normal, []) returned an error: shutdown: failed to start child: RetWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (ArgumentError) could not start Cowboy2 adapter, missing option :key/:keyfile
            (plug_cowboy 2.1.3) lib/plug/cowboy.ex:310: Plug.Cowboy.fail/1
            (plug_cowboy 2.1.3) lib/plug/cowboy.ex:62: Plug.Cowboy.args/4
            (plug_cowboy 2.1.3) lib/plug/cowboy.ex:170: Plug.Cowboy.child_spec/1
            (phoenix 1.4.17) lib/phoenix/endpoint/cowboy2_adapter.ex:44: Phoenix.Endpoint.Cowboy2Adapter.child_spec/3
            (phoenix 1.4.17) lib/phoenix/endpoint/supervisor.ex:108: anonymous fn/6 in Phoenix.Endpoint.Supervisor.server_children/4
            (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
            (phoenix 1.4.17) lib/phoenix/endpoint/supervisor.ex:99: Phoenix.Endpoint.Supervisor.server_children/4
            (phoenix 1.4.17) lib/phoenix/endpoint/supervisor.ex:59: Phoenix.Endpoint.Supervisor.init/1
```

(commit ca443c520f5a2cb9f0e5da1367b72bddedc8a38a)

**Comment by mkg20001** [comment]
I've got most things running on nixOS now https://github.com/mkg20001/hubs-flake

Just this bug left (development is done on ubuntu, production later nixOS - but issue occurs on both)

**Comment by justincolangelo** [comment]
Have you solved this? We are experiencing the same issue. Tried updating to Elixir 1.11 OTP 23 to fix other things. This one remains.
