### ISSUE TITLE
Running Docker container with docker-compose fails with: (CompileError) module Mix.Task.Compiler is not loaded and could not be found

### ISSUE THREAD

**Issue by SharkyRawr** [mozilla/reticulum#503]
```
ret_1  | ==> dns
ret_1  | Compiling 7 files (.ex)
ret_1  | Generated dns app
ret_1  | ===> Fetching rebar3_hex v6.11.4
ret_1  | ===> Downloaded package, caching at /root/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.11.4.tar
ret_1  | ===> Fetching hex_core v0.7.1
ret_1  | ===> Downloaded package, caching at /root/.cache/rebar3/hex/hexpm/packages/hex_core-0.7.1.tar
ret_1  | ===> Fetching verl v1.0.2
ret_1  | ===> Downloaded package, caching at /root/.cache/rebar3/hex/hexpm/packages/verl-1.0.2.tar
ret_1  | ===> Compiling verl
ret_1  | ===> Compiling hex_core
ret_1  | ===> Compiling rebar3_hex
ret_1  | ===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
ret_1  | ===> Compiling sleeplocks
ret_1  | ===> Compiling metrics
ret_1  | ===> Compiling unicode_util_compat
ret_1  | ===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
ret_1  | ===> Compiling idna
ret_1  | ==> bunt
ret_1  | Compiling 2 files (.ex)
ret_1  | Generated bunt app
ret_1  | ==> gettext
ret_1  | warning: the dependency :gettext requires Elixir "~> 1.6" but you are running on v1.5.3
ret_1  | Compiling 1 file (.yrl)
ret_1  | Compiling 1 file (.erl)
ret_1  | Compiling 20 files (.ex)
ret_1  |
ret_1  | == Compilation error in file lib/mix/tasks/compile.gettext.ex ==
ret_1  | ** (CompileError) lib/mix/tasks/compile.gettext.ex:2: module Mix.Task.Compiler is not loaded and could not be found
ret_1  |     (elixir) expanding macro: Kernel.use/1
ret_1  |     lib/mix/tasks/compile.gettext.ex:2: Mix.Tasks.Compile.Gettext (module)
ret_1  | could not compile dependency :gettext, "mix compile" failed. You can recompile this dependency with "mix deps.compile gettext", update it with "mix deps.update gettext" or clean it with "mix deps.clean gettext"
ret_1  | ==> gettext
ret_1  | warning: the dependency :gettext requires Elixir "~> 1.6" but you are running on v1.5.3
ret_1  | Compiling 20 files (.ex)
ret_1  |
ret_1  | == Compilation error in file lib/mix/tasks/compile.gettext.ex ==
ret_1  | ** (CompileError) lib/mix/tasks/compile.gettext.ex:2: module Mix.Task.Compiler is not loaded and could not be found
ret_1  |     (elixir) expanding macro: Kernel.use/1
ret_1  |     lib/mix/tasks/compile.gettext.ex:2: Mix.Tasks.Compile.Gettext (module)
ret_1  | could not compile dependency :gettext, "mix compile" failed. You can recompile this dependency with "mix deps.compile gettext", update it with "mix deps.update gettext" or clean it with "mix deps.clean gettext"
ret_1  | warning: the dependency :gettext requires Elixir "~> 1.6" but you are running on v1.5.3
ret_1  | ==> gettext
ret_1  | Compiling 20 files (.ex)
ret_1  |
ret_1  | == Compilation error in file lib/mix/tasks/compile.gettext.ex ==
ret_1  | ** (CompileError) lib/mix/tasks/compile.gettext.ex:2: module Mix.Task.Compiler is not loaded and could not be found
ret_1  |     (elixir) expanding macro: Kernel.use/1
ret_1  |     lib/mix/tasks/compile.gettext.ex:2: Mix.Tasks.Compile.Gettext (module)
ret_1  | could not compile dependency :gettext, "mix compile" failed. You can recompile this dependency with "mix deps.compile gettext", update it with "mix deps.update gettext" or clean it with "mix deps.clean gettext"
```

**Comment by SharkyRawr** [comment]
Updating to elixir:1.6 or better yet elixir:1.12 fixes this issue and more down the line:

```
diff --git a/Dockerfile b/Dockerfile
index 9230a121..b474511d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
-FROM elixir:1.5
+FROM elixir:1.12
 RUN apt-get update -qq && apt-get install -y inotify-tools
-RUN curl -so- -L https://yarnpkg.com/install.sh | bash
+#RUN curl -so- -L https://yarnpkg.com/install.sh | bash
 RUN mkdir /ret
 WORKDIR        /ret
 COPY mix.exs /ret/mix.exs
```
