### ISSUE TITLE
Docs request Elixir 1.8 but Phoenix requests 1.12

### ISSUE THREAD

**Issue by nonlin** [mozilla/reticulum#548]
Attempting with 1.12 anyways on the step iex -S mix phx.server

I get 

```
Last message: :cachex_warmer
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
iex(1)> [error] GenServer #PID<0.961.0> terminating
** (stop) :enoent
    (elixir 1.12.0) lib/system.ex:1041: System.cmd("df", ["-k", "storage/dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:10: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.9) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.9) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.9) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
iex(1)> [info] <TheEnd> no more connections
iex(1)> [info] Application ret exited: shutdown
iex(1)>

```

**Comment by albirrkarim** [comment]
Im runing this reticulum with elixir 1.12 and erlang 23 and it works.

**Comment by brianpeiris** [comment]
The error mentions that the `storage/dev` directory is missing, so you might have to create that, or it could be an erlang/elixir version mismatch as Al Birr stated.

**Comment by danflu** [comment]
I'm having this exact issue when trying to run reticulum in Windows 11. The directory storage/dev is created. I can't understand exactly what is the cause of this erro message... Could you please help me ?

```
C:\mozilla-hubs\reticulum>iex -S mix phx.server
[debug] QUERY OK db=0.0ms queue=16.0ms idle=1562.0ms
CREATE SCHEMA IF NOT EXISTS ret0 []
[debug] QUERY OK db=0.0ms idle=0.0ms
CREATE SCHEMA IF NOT EXISTS coturn []
[debug] QUERY OK db=0.0ms idle=0.0ms
ALTER DATABASE ret_dev SET search_path TO ret0 []
[info] Already up
[debug] QUERY OK db=0.0ms idle=15.0ms
INSERT INTO coturn.turn_secret (realm, value, inserted_at, updated_at) values ($1, $2, now(), now()) ["ret", "3d5a8f0aa3cfd763106592842a1549d0"]
[debug] QUERY OK db=0.0ms idle=0.0ms
DELETE FROM coturn.turn_secret WHERE inserted_at < now() - interval '15 minutes' []
[info] Running RetWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (https)
[info] Access RetWeb.Endpoint at https://localhost:4000
Interactive Elixir (1.12.3) - press Ctrl+C to exit (type h() ENTER for help)
[error] GenServer #PID<0.948.0> terminating
** (stop) :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("df", ["-k", "storage/dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:27: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
[error] GenServer #PID<0.969.0> terminating
** (stop) :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("df", ["-k", "storage/dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:27: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
[error] GenServer #PID<0.970.0> terminating
** (stop) :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("df", ["-k", "storage/dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:27: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
[error] GenServer #PID<0.972.0> terminating
** (stop) :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("df", ["-k", "storage/dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:27: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
```

**Comment by danflu** [comment]
Also running terminal as administrator

**Comment by danflu** [comment]
Even if I change storage_path in devs.exs to absolute path:

```
config :ret, Ret.Storage,
  host: "https://#{host}:4000",
  storage_path: "C:\\mozilla-hubs\\reticulum\\storage\\dev",
  ttl: 60 * 60 * 24
```

I still get the error:

```
State: {{:cache, :storage_used, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit, nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.StorageUsed, nil}]}, nil}
iex(1)> [error] GenServer #PID<0.2322.0> terminating
** (stop) :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("df", ["-k", "C:\\mozilla-hubs\\reticulum\\storage\\dev"], [])
    (ret 1.0.0) lib/ret/storage_used.ex:27: Ret.StorageUsed.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.StorageUsed.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
```

**Comment by danflu** [comment]
Any idea or workaround for this ?
