### ISSUE TITLE
Running RetWeb.Endpoint terminated Server:exapmle.com:4000 (https)(Plug.Conn.NotSentError) a response was neither set nor sent from the connection

### ISSUE THREAD

**Issue by monukbizsoft** [mozilla/reticulum#652]
Hi

First I am facing same issue in local System Then I have created a new issue and resolved it: https://github.com/mozilla/reticulum/issues/648

But now I am facing same error on live server 

Server VPS with ubuntu 20

Please check error: 
```
== Compilation error in file lib/ret/schema.ex ==
** (CompileError) lib/ret/schema.ex:39: call to local macro is_struct/1 conflicts with imported Kernel.is_struct/1, please rename the local macro or remove the conflicting import
    (elixir 1.12.3) expanding macro: Kernel.and/2
    lib/ret/schema.ex:39: Ret.Schema.is_schema/1
    (elixir 1.12.3) expanding macro: Kernel.and/2
    lib/ret/schema.ex:40: Ret.Schema.is_schema/1
    (elixir 1.12.3) expanding macro: Kernel.Utils.defguard/2
    lib/ret/schema.ex: Ret.Schema.is_schema/1
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I have added .asdf/shims in first possition into $PATH file
```
**echo $PATH**
/root/.asdf/shims:/root/.asdf/bin:/root/.nvm/versions/node/v16.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I am using below version of elixir and erlang
```
**# asdf current**
elixir          1.12.3          /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
erlang          23.3            /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
```

Thanks

**Comment by monukbizsoft** [comment]
Now I am changed the version of elixir and erlang

now I am using elixir and erlang
**# asdf current**
```
elixir      1.8.2         /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
erlang      22.3.4.26     /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
```

Then I am not able to access the front-end of hub because reticulum is not started yet.

I have run the the below commmads from terminal
```
MIX_ENV=prod mix compile
PORT=4000 MIX_ENV=prod mix phx.server
```

Now reticulum is working but it return 500 error

Please check screenshots: 
![Screenshot at Dec 19 13-07-10](https://user-images.githubusercontent.com/119565686/208372465-0a76c8a4-7e50-4d3b-b644-5c827455eb6e.png)
![Screenshot at Dec 19 13-08-52](https://user-images.githubusercontent.com/119565686/208372472-738bc04b-933f-4b49-af56-b1238672d870.png)

Error: 
```
[error] #PID<0.955.0> running RetWeb.Endpoint (connection #PID<0.954.0>, stream id 1) terminated
Server:exapmle.com:4000 (https)
Request: GET /
** (exit) an exception was raised:
    ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:67: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy) /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy) /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
